### ISSUE TITLE
x64版にてエラーを吐く

### ISSUE THREAD

**Issue by apapanda** [Nishisonic/QuestStateEx#5]
[script.log](https://github.com/Nishisonic/QuestStateEx/files/2264778/script.log)
一部の任務進歩がカウントされない。

**Comment by Nishisonic** [comment]
すいません、使う関数間違えてました
修正します

**Comment by Nishisonic** [comment]
`a6de32c`で修正しました。

**Comment by apapanda** [comment]
早々の修正ありがとうございます。
取り敢えず一週間程様子を見てみます。
